# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kpj3VitVsAgCKjL1HO9hqaOM7rOus4y2
"""

print("Hello World")

a=5
b=2
c=a+b
print(c)

a=int(input())
b=int(input())
S=(a+b) * 2
print(S)

a=4
b=2
c=3
x=(a^2+b^2-c^3)/2
print(c)

a=5
b=input()
c=a*b
print(b)
print(c)

a=int(input())
b=int(input())
c=(a+b)**2
print(c)

a=15
b=10
C=int(input())
c=(a+b)/C
print(c)

a=5
b=2
c=a**2+2*a*b+b^2
print(c)

a=6
h=2
s=1/2*a*h
print(s)
b=3
c=4
p=a+b+c
print(p)

a=5
b=3
c=((a^3+14)/5)*b
print(c)

a=8
s=a**2
print(s)
n=2
c=a//2
print(c)

a=int(input())
b=int(input())
c=a*b
print(c)

a=int(input())
b=int(input())
c=a/b
print(c)

a=int(input())
b=int(input())
c=(a/a)//(b/b)
print(c)

sec=int(input())
h=sec//3600
m=(sec-h*3600)//60
s=sec % 60
print(h,'час',m,'мин',s,'сек')

def solve(n):
  n1=n
  n2=int(str(n)*2)
  n3=int(str(n)*3)
  print(n1+n2+n3)

solve(5)