# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IEqqszhMrA8LJMAjzzVp-LN2SF-PqqRo
"""

Month = int(input())
if Month == 1:
  print('January')
elif Month == 2:
  print('February')
elif Month == 3:
  print('March')
elif Month == 4:
  print('April')
elif Month == 5:
  print('May')
elif Month == 6:
  print('June')
elif Month == 7:
  print('July')
elif Month == 8:
  print('August')
elif Month == 9:
  print('September')
elif Month == 10:
  print('October')
elif Month == 11:
  print('November')
elif  Month == 12:
  print('December')
else: print(0)

N = int(input())
if (N % 2):
 print('нечетн')
else: print('четн')

N = int(input())
if N > 40:
  print('stonks')
elif N < 40:
  print('not stonks')

def is_year_leap():
  year=int(input())
  if year % 4 !=0 or (year % 100==0 and year % 400==0):
    return False
  else:
    return True
is_year_leap()

def is_prime():
  n=int(input())
  a=False
  for i in range(2,n):
    if n%i==0:
      a=False
      break
    else:
      a=True
  return(a)
is_prime()

a=float(input())
b=float(input())

if a == b*3.6 or b== (-138/2)**1.3:
  if a== b*3.6 or b== (-69/28^5.1)*4: 
 
   print ("a это:", a,"b это:", b)

a=int(input())
b=int(input())
c=int(input())
d=int(input())
e=int(input())
if (a==b) or (a==c) or (a==d) or (a==e) or (b==c) or (b==d) or (b==e) or (c==d) or (c==e) or (d==e):
   print("Не все числа уникальны")
else:
   print("Все числа уникальны")
cnt=0
if a%2==0:
  cnt=cnt+1
if b%2==0:
  cnt=cnt+1
if c%2==0:
  cnt=cnt+1
if d%2==0:
  cnt=cnt+1
if e%2==0:
  cnt=cnt+1
print("Количество четных чисел =", cnt)
cnt2=0
if a<0:
  cnt2=cnt2+1
if b<0:
  cnt2=cnt2+1
if c<0:
  cnt2=cnt2+1
if d<0:
  cnt2=cnt2+1
if e<0:
  cnt2=cnt2+1
print("Количество отрицательных чисел =", cnt2)
cnt3=0
if -256<=a<=1024:
  cnt3=cnt3+1
if -256<=b<=1024:
  cnt3=cnt3+1
if -256<=c<=1024:
  cnt3=cnt3+1
if -256<=d<=1024:
  cnt3=cnt3+1
if -256<=e<=1024:
  cnt3=cnt3+1
print("Количество чисел на промежутке [-256;1024] =",cnt3)